# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

variables:
  AzureResourceGroup: 'axretro-rg'
  AzureRegion: 'uksouth'
  skipComponentGovernanceDetection: 'true' # Disable internal to Microsoft injected policy

stages:
- stage: Prep
  displayName: 'Create or update target infrastructure'
  jobs:
  - job: 'ResourceGroup'
    displayName: 'Ensure resource group exists'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure On Line Services(2482da3d-7516-4b32-9057-d311caa99664)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az group create --name $(AzureResourceGroup) --location $(AzureRegion)'

